on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    container:
      image: bioconductor/bioconductor_full:devel
      steps:
      - name: Checkout Repository
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          BiocManager::install(c('remotes', 'rcmdcheck'))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
